export type LibraryMeal = {
  id: string
  name: string
  emoji: string
  mealType: 'breakfast' | 'lunch' | 'dinner' | 'snack'
  calories: number
  proteinG: number
  prepMinutes: number
  costGBP: number
  tags: string[]
  description: string
  ingredients: string[]
  steps: string[]
  imageUrl?: string
}

// ─── BREAKFAST (6) ────────────────────────────────────────────────────────────

const overnightOats: LibraryMeal = {
  id: 'overnight-oats',
  name: 'Overnight Oats with Berries',
  emoji: '🫙',
  mealType: 'breakfast',
  calories: 350,
  proteinG: 14,
  prepMinutes: 5,
  costGBP: 0.90,
  tags: ['high-fibre', 'batch-cook', 'under-500-kcal', 'ManvFat-friendly'],
  description: 'Creamy oats soaked overnight with mixed berries and a hit of protein. Grab and go.',
  ingredients: [
    '80g rolled oats',
    '200ml semi-skimmed milk',
    '100g Greek yoghurt',
    '1 tbsp chia seeds',
    '100g mixed berries',
    '1 tsp honey',
  ],
  steps: [
    'Add oats, milk, yoghurt, and chia seeds to a jar or container. Stir well.',
    'Cover and refrigerate overnight (or at least 4 hours).',
    'In the morning, top with berries and drizzle with honey.',
    'Add a splash more milk if you prefer a looser consistency.',
  ],
  imageUrl: '/images/recipes/overnight-oats.webp',
}

const scrambledEggsToast: LibraryMeal = {
  id: 'scrambled-eggs-toast',
  name: 'Scrambled Eggs & Wholemeal Toast',
  emoji: '🍳',
  mealType: 'breakfast',
  calories: 400,
  proteinG: 28,
  prepMinutes: 10,
  costGBP: 1.20,
  tags: ['high-protein', 'quick', 'ManvFat-friendly'],
  description: 'Fluffy scrambled eggs on seeded wholemeal toast. Simple, filling and packed with protein.',
  ingredients: [
    '3 eggs',
    '2 slices wholemeal bread',
    '1 tbsp butter',
    '30ml semi-skimmed milk',
    'Salt and black pepper',
    'Handful of spinach (optional)',
  ],
  steps: [
    'Crack eggs into a bowl, add milk, season with salt and pepper, and whisk.',
    'Melt butter in a non-stick pan over low heat.',
    "Pour in eggs. Stir slowly and continuously with a spatula until just set. Don't overcook.",
    'Toast the bread. Wilt spinach in the pan for 30 seconds if using.',
    'Serve eggs immediately on toast.',
  ],
  imageUrl: '/images/recipes/scrambled-eggs.webp',
}

const greekYoghurtParfait: LibraryMeal = {
  id: 'greek-yoghurt-parfait',
  name: 'Greek Yoghurt Parfait',
  emoji: '🍓',
  mealType: 'breakfast',
  calories: 310,
  proteinG: 20,
  prepMinutes: 5,
  costGBP: 1.60,
  tags: ['high-protein', 'quick', 'under-500-kcal', 'ManvFat-friendly'],
  description: 'Layers of thick Greek yoghurt, granola, and fresh fruit. Ready in 5 minutes.',
  ingredients: [
    '200g full-fat Greek yoghurt',
    '30g low-sugar granola',
    '1 banana, sliced',
    '80g strawberries',
    '1 tsp honey',
  ],
  steps: [
    'Spoon half the yoghurt into a glass or bowl.',
    'Add half the granola and banana.',
    'Layer the remaining yoghurt on top.',
    'Top with strawberries, remaining granola, and a drizzle of honey.',
  ],
  imageUrl: '/images/recipes/greek-yoghurt-parfait.webp',
}

const proteinSmoothie: LibraryMeal = {
  id: 'banana-protein-smoothie',
  name: 'Banana Protein Smoothie',
  emoji: '🥤',
  mealType: 'breakfast',
  calories: 370,
  proteinG: 30,
  prepMinutes: 5,
  costGBP: 1.30,
  tags: ['high-protein', 'quick', 'under-500-kcal'],
  description: 'A thick, creamy smoothie that keeps you full until lunch. Great post-workout too.',
  ingredients: [
    '1 banana (frozen is best)',
    '1 scoop vanilla protein powder',
    '200ml semi-skimmed milk',
    '1 tbsp peanut butter',
    '1 tsp honey',
    '3–4 ice cubes',
  ],
  steps: [
    'Add all ingredients to a blender.',
    'Blend on high for 30–60 seconds until smooth.',
    'Taste and add more honey if needed.',
    'Drink immediately.',
  ],
  imageUrl: '/images/recipes/banana-protein-smoothie.webp',
}

const avocadoEggsToast: LibraryMeal = {
  id: 'avocado-eggs-toast',
  name: 'Avocado & Poached Egg Toast',
  emoji: '🥑',
  mealType: 'breakfast',
  calories: 460,
  proteinG: 22,
  prepMinutes: 12,
  costGBP: 2.10,
  tags: ['healthy-fats', 'high-protein', 'under-500-kcal'],
  description: 'Smashed avocado on sourdough topped with a perfectly poached egg. Weekend treat vibes on a weekday.',
  ingredients: [
    '2 slices sourdough bread',
    '1 ripe avocado',
    '2 eggs',
    '1 tsp lemon juice',
    'Chilli flakes',
    'Salt and black pepper',
  ],
  steps: [
    'Toast the sourdough until golden.',
    'Halve the avocado, remove the stone, and scoop into a bowl. Add lemon juice, salt, and pepper. Mash roughly.',
    'Bring a pan of water to a gentle simmer. Add a splash of vinegar.',
    'Crack each egg into a small cup. Swirl the water and slide eggs in. Cook for 3 minutes for a runny yolk.',
    'Spread avocado on toast, top with eggs, and scatter chilli flakes.',
  ],
  imageUrl: '/images/recipes/avocado-poached-egg.webp',
}

const bananaPorridge: LibraryMeal = {
  id: 'banana-porridge',
  name: 'Banana & Honey Porridge',
  emoji: '🍌',
  mealType: 'breakfast',
  calories: 340,
  proteinG: 10,
  prepMinutes: 8,
  costGBP: 0.70,
  tags: ['high-fibre', 'quick', 'budget-friendly', 'under-500-kcal', 'ManvFat-friendly'],
  description: 'Classic warming porridge with sliced banana and a drizzle of honey. Cheap, filling, and comforting.',
  ingredients: [
    '80g rolled oats',
    '300ml semi-skimmed milk',
    '1 banana',
    '1 tsp honey',
    'Pinch of cinnamon',
    'Pinch of salt',
  ],
  steps: [
    'Add oats, milk, and a pinch of salt to a small pan.',
    'Cook over medium heat, stirring regularly, for 5–6 minutes until thick and creamy.',
    'Pour into a bowl. Top with sliced banana, a drizzle of honey, and a pinch of cinnamon.',
  ],
  imageUrl: '/images/recipes/banana-porridge.webp',
}

// ─── LUNCH (5) ────────────────────────────────────────────────────────────────

const chickenCaesarWrap: LibraryMeal = {
  id: 'chicken-caesar-wrap',
  name: 'Chicken Caesar Wrap',
  emoji: '🌯',
  mealType: 'lunch',
  calories: 430,
  proteinG: 40,
  prepMinutes: 8,
  costGBP: 2.80,
  tags: ['high-protein', 'quick', 'ManvFat-friendly'],
  description: 'Grilled chicken, crisp romaine, and Caesar dressing wrapped in a wholemeal tortilla. Proper lunch.',
  ingredients: [
    '1 large wholemeal tortilla wrap',
    '150g cooked chicken breast, sliced',
    '2 large handfuls romaine lettuce',
    '2 tbsp light Caesar dressing',
    '15g parmesan shavings',
    'Black pepper',
  ],
  steps: [
    'Lay the wrap flat on a board.',
    'Layer romaine lettuce down the centre.',
    'Add chicken and parmesan. Drizzle with Caesar dressing.',
    'Season with black pepper.',
    'Fold in the sides and roll up firmly. Slice in half to serve.',
  ],
  imageUrl: '/images/recipes/chicken-caesar-wrap.webp',
}

const tunaJacketPotato: LibraryMeal = {
  id: 'tuna-sweetcorn-jacket',
  name: 'Tuna & Sweetcorn Jacket Potato',
  emoji: '🥔',
  mealType: 'lunch',
  calories: 460,
  proteinG: 36,
  prepMinutes: 60,
  costGBP: 1.80,
  tags: ['high-protein', 'budget-friendly', 'ManvFat-friendly'],
  description: 'The ultimate comforting lunch. Fluffy baked potato loaded with tuna and sweetcorn.',
  ingredients: [
    '1 large baking potato',
    '1 tin tuna in water (drained)',
    '50g sweetcorn (tinned or frozen)',
    '2 tbsp light mayonnaise',
    '½ lemon',
    'Salt and black pepper',
  ],
  steps: [
    'Preheat oven to 200°C. Pierce potato all over with a fork.',
    'Bake for 50–60 minutes until the skin is crispy and the inside is soft. (Microwave for 8 minutes to speed things up, then crisp in the oven for 15 minutes.)',
    'Mix drained tuna with sweetcorn, mayo, and a squeeze of lemon. Season well.',
    'Split the potato open, fluff the insides, and load with the tuna mix.',
  ],
  imageUrl: '/images/recipes/tuna-jacket-potato.webp',
}

const prawnStirFryNoodles: LibraryMeal = {
  id: 'prawn-stir-fry-noodles',
  name: 'Prawn Stir-fry Noodles',
  emoji: '🍜',
  mealType: 'lunch',
  calories: 420,
  proteinG: 34,
  prepMinutes: 15,
  costGBP: 3.50,
  tags: ['high-protein', 'quick', 'low-fat'],
  description: 'King prawns and veg in a soy and ginger sauce tossed through egg noodles. Ready in 15 minutes.',
  ingredients: [
    '200g raw king prawns',
    '150g straight-to-wok egg noodles',
    '1 red pepper, sliced',
    '100g sugar snap peas',
    '3 tbsp soy sauce',
    '1 tsp sesame oil',
    '1 garlic clove, minced',
    '1 tsp fresh ginger, grated',
  ],
  steps: [
    'Heat oil in a wok over high heat. Stir-fry garlic and ginger for 30 seconds.',
    'Add pepper and sugar snap peas. Stir-fry for 2 minutes.',
    'Add prawns and cook for 2–3 minutes until pink.',
    'Add noodles and soy sauce. Toss everything together for 2 minutes.',
    'Drizzle with sesame oil and serve immediately.',
  ],
  imageUrl: '/images/recipes/prawn-noodles.webp',
}

const lentilSoup: LibraryMeal = {
  id: 'lentil-vegetable-soup',
  name: 'Red Lentil & Vegetable Soup',
  emoji: '🍲',
  mealType: 'lunch',
  calories: 290,
  proteinG: 18,
  prepMinutes: 25,
  costGBP: 1.20,
  tags: ['high-fibre', 'budget-friendly', 'batch-cook', 'vegetarian', 'under-500-kcal', 'ManvFat-friendly'],
  description: 'Hearty, filling, and dirt cheap. Make a big batch on Sunday and eat it all week.',
  ingredients: [
    '150g red lentils',
    '1 onion, diced',
    '2 carrots, diced',
    '2 garlic cloves',
    '400ml vegetable stock',
    '1 tsp cumin',
    '1 tsp turmeric',
    '1 tbsp olive oil',
  ],
  steps: [
    'Heat oil in a large pan. Fry onion and carrots for 5 minutes until softened.',
    'Add garlic, cumin, and turmeric. Cook for 1 minute.',
    'Add lentils and stock. Bring to a boil, then simmer for 15 minutes until lentils are soft.',
    'Blend half the soup for a thicker consistency, or leave chunky.',
    'Season and serve with crusty bread.',
  ],
  imageUrl: '/images/recipes/lentil-soup.webp',
}

const greekSaladChicken: LibraryMeal = {
  id: 'greek-salad-chicken',
  name: 'Greek Salad with Feta & Chicken',
  emoji: '🥗',
  mealType: 'lunch',
  calories: 390,
  proteinG: 40,
  prepMinutes: 10,
  costGBP: 3.20,
  tags: ['high-protein', 'low-carb', 'quick', 'under-500-kcal', 'ManvFat-friendly'],
  description: 'Crisp salad with juicy chicken, creamy feta, olives, and a lemon dressing. Light but satisfying.',
  ingredients: [
    '150g cooked chicken breast, sliced',
    '½ cucumber, chopped',
    '150g cherry tomatoes, halved',
    '60g feta cheese, crumbled',
    '30g pitted kalamata olives',
    '2 tbsp olive oil',
    '1 tbsp lemon juice',
    '½ tsp dried oregano',
  ],
  steps: [
    'Combine cucumber, tomatoes, and olives in a bowl.',
    'Whisk olive oil, lemon juice, and oregano to make the dressing.',
    'Top the salad with sliced chicken and crumbled feta.',
    'Drizzle dressing over and toss gently.',
  ],
  imageUrl: '/images/recipes/greek-salad-chicken.webp',
}

// ─── DINNER (9) ───────────────────────────────────────────────────────────────

const turkeyBolognese: LibraryMeal = {
  id: 'turkey-bolognese',
  name: 'Turkey Mince Bolognese',
  emoji: '🍝',
  mealType: 'dinner',
  calories: 520,
  proteinG: 48,
  prepMinutes: 30,
  costGBP: 4.20,
  tags: ['high-protein', 'batch-cook', 'ManvFat-friendly'],
  description: 'All the comfort of a classic spag bol with turkey mince instead. Leaner and just as tasty.',
  ingredients: [
    '400g turkey mince',
    '1 onion, diced',
    '2 garlic cloves, minced',
    '400g tin chopped tomatoes',
    '2 tbsp tomato purée',
    '1 tsp dried oregano',
    '300g wholewheat spaghetti',
    '1 tbsp olive oil',
  ],
  steps: [
    'Cook spaghetti according to packet instructions.',
    'Heat oil in a pan. Fry onion and garlic until softened, about 5 minutes.',
    'Add turkey mince. Brown well, breaking up lumps.',
    'Stir in tomatoes, tomato purée, and oregano. Simmer for 15 minutes.',
    'Season generously and serve over spaghetti.',
  ],
  imageUrl: '/images/recipes/turkey-bolognaise.webp',
}

const bakedSalmonRoastedVeg: LibraryMeal = {
  id: 'baked-salmon-roasted-veg',
  name: 'Baked Salmon with Roasted Veg',
  emoji: '🍠',
  mealType: 'dinner',
  calories: 530,
  proteinG: 44,
  prepMinutes: 35,
  costGBP: 5.50,
  tags: ['high-protein', 'healthy-fats', 'ManvFat-friendly'],
  description: 'A classic healthy dinner: baked salmon with a tray of roasted Mediterranean vegetables.',
  ingredients: [
    '200g salmon fillet',
    '1 courgette, chopped',
    '1 red pepper, sliced',
    '200g cherry tomatoes',
    '1 tbsp olive oil',
    '½ lemon',
    '1 tsp mixed herbs',
    'Salt and pepper',
  ],
  steps: [
    'Preheat oven to 200°C. Toss courgette, pepper, and tomatoes with olive oil, herbs, salt, and pepper on a large baking tray. Roast for 15 minutes.',
    'Season salmon with lemon juice, salt, and pepper.',
    'Push veg to the sides and place salmon on the tray. Bake for a further 12–15 minutes.',
    'Serve salmon on the veg with a wedge of lemon.',
  ],
  imageUrl: '/images/recipes/salmon-roasted-veg.webp',
}

const chickenTikkaMasala: LibraryMeal = {
  id: 'chicken-tikka-masala',
  name: 'Lighter Chicken Tikka Masala',
  emoji: '🍛',
  mealType: 'dinner',
  calories: 490,
  proteinG: 46,
  prepMinutes: 30,
  costGBP: 4.00,
  tags: ['high-protein', 'batch-cook', 'ManvFat-friendly'],
  description: "A lighter version of the nation's favourite: big flavour, less cream. Serve with basmati rice.",
  ingredients: [
    '400g chicken breast, diced',
    '1 onion, diced',
    '2 garlic cloves, minced',
    '1 tin light coconut milk',
    '2 tbsp tikka masala paste',
    '400g tin chopped tomatoes',
    '1 tbsp Greek yoghurt',
    'Fresh coriander to serve',
  ],
  steps: [
    'Fry onion and garlic in oil for 5 minutes. Add tikka paste and cook for 2 minutes.',
    'Add chicken and brown on all sides.',
    'Pour in tomatoes and coconut milk. Simmer for 20 minutes until chicken is cooked through.',
    'Stir in yoghurt off the heat.',
    'Scatter coriander and serve with basmati rice.',
  ],
  imageUrl: '/images/recipes/chicken-tikka-masala.webp',
}

const beefChilli: LibraryMeal = {
  id: 'beef-chilli',
  name: 'Lean Beef Chilli',
  emoji: '🫘',
  mealType: 'dinner',
  calories: 500,
  proteinG: 44,
  prepMinutes: 40,
  costGBP: 4.50,
  tags: ['high-protein', 'batch-cook', 'ManvFat-friendly'],
  description: 'Rich, warming chilli made with lean beef mince and kidney beans. Great for batch cooking.',
  ingredients: [
    '400g lean beef mince (5% fat)',
    '400g tin kidney beans, drained',
    '400g tin chopped tomatoes',
    '1 onion, diced',
    '2 garlic cloves',
    '2 tsp chilli powder',
    '1 tsp cumin',
    '1 tsp smoked paprika',
  ],
  steps: [
    'Brown the mince in a pan over high heat. Drain off any excess fat.',
    'Add onion and garlic. Cook for 5 minutes.',
    'Add chilli powder, cumin, and paprika. Stir for 1 minute.',
    'Pour in tomatoes and kidney beans. Simmer for 25 minutes.',
    'Season well. Serve with rice, a baked potato, or flatbread.',
  ],
  imageUrl: '/images/recipes/beef-chilli.webp',
}

const prawnVegStirFry: LibraryMeal = {
  id: 'prawn-veg-stir-fry',
  name: 'Prawn & Vegetable Stir-fry',
  emoji: '🦐',
  mealType: 'dinner',
  calories: 380,
  proteinG: 36,
  prepMinutes: 20,
  costGBP: 4.80,
  tags: ['high-protein', 'quick', 'low-fat', 'under-500-kcal', 'ManvFat-friendly'],
  description: 'Fragrant king prawns with colourful veg in a soy and ginger sauce. Serve with jasmine rice.',
  ingredients: [
    '300g raw king prawns',
    '1 red pepper, sliced',
    '200g broccoli florets',
    '1 carrot, julienned',
    '3 tbsp soy sauce',
    '1 tbsp oyster sauce',
    '1 tsp sesame oil',
    '2 garlic cloves',
  ],
  steps: [
    'Heat oil in a wok over high heat. Fry garlic for 30 seconds.',
    'Add pepper, broccoli, and carrot. Stir-fry for 3 minutes.',
    'Add prawns and cook for 2–3 minutes until pink.',
    'Pour in soy sauce and oyster sauce. Toss to coat.',
    'Drizzle with sesame oil and serve over jasmine rice.',
  ],
  imageUrl: '/images/recipes/prawn-veg-stir-fry.webp',
}

const cottagePieSweetPotato: LibraryMeal = {
  id: 'cottage-pie-sweet-potato',
  name: 'Cottage Pie with Sweet Potato Mash',
  emoji: '🥧',
  mealType: 'dinner',
  calories: 560,
  proteinG: 42,
  prepMinutes: 50,
  costGBP: 5.00,
  tags: ['high-protein', 'batch-cook', 'ManvFat-friendly'],
  description: 'A healthier take on the classic: lean beef mince topped with sweet potato mash. Pure comfort food.',
  ingredients: [
    '400g lean beef mince',
    '2 large sweet potatoes',
    '1 onion, diced',
    '2 carrots, diced',
    '200ml beef stock',
    '1 tbsp Worcestershire sauce',
    '2 tbsp tomato purée',
    '1 tbsp butter',
  ],
  steps: [
    'Brown mince in a pan. Add onion and carrots and cook for 5 minutes.',
    'Stir in tomato purée, Worcestershire sauce, and stock. Simmer for 20 minutes.',
    'Meanwhile, peel and cube sweet potatoes. Boil for 15 minutes, drain, and mash with butter.',
    'Pour mince into a baking dish. Top with sweet potato mash and rough up with a fork.',
    'Bake at 200°C for 20 minutes until golden on top.',
  ],
  imageUrl: '/images/recipes/cottage-pie-sweet-potato.webp',
}

const chickenChorizo: LibraryMeal = {
  id: 'chicken-chorizo-pasta',
  name: 'Chicken & Chorizo Pasta',
  emoji: '🍝',
  mealType: 'dinner',
  calories: 580,
  proteinG: 48,
  prepMinutes: 25,
  costGBP: 4.80,
  tags: ['high-protein', 'quick', 'ManvFat-friendly'],
  description: 'Smoky chorizo with tender chicken and pasta in a rich tomato sauce. Everyone loves this one.',
  ingredients: [
    '300g chicken breast, diced',
    '80g chorizo, sliced',
    '300g penne pasta',
    '400g tin chopped tomatoes',
    '1 onion, diced',
    '2 garlic cloves',
    '1 tsp smoked paprika',
    'Fresh parsley to serve',
  ],
  steps: [
    'Cook pasta according to packet instructions.',
    'Fry chorizo in a dry pan for 2 minutes until oils release. Add onion and garlic.',
    'Add chicken and brown on all sides. Stir in paprika.',
    'Pour in tomatoes. Simmer for 15 minutes.',
    'Toss with drained pasta and scatter parsley.',
  ],
  imageUrl: '/images/recipes/chicken-chorizo-pasta.webp',
}

const lemonHerbChicken: LibraryMeal = {
  id: 'lemon-herb-chicken-new-potatoes',
  name: 'Lemon Herb Chicken with New Potatoes',
  emoji: '🍗',
  mealType: 'dinner',
  calories: 490,
  proteinG: 46,
  prepMinutes: 40,
  costGBP: 4.20,
  tags: ['high-protein', 'ManvFat-friendly'],
  description: 'Marinated chicken breasts roasted with new potatoes, garlic, and fresh herbs. Dead simple.',
  ingredients: [
    '2 chicken breasts',
    '400g new potatoes, halved',
    '2 tbsp olive oil',
    '2 garlic cloves, minced',
    '1 lemon',
    '1 tsp dried rosemary',
    '1 tsp dried thyme',
    'Salt and pepper',
  ],
  steps: [
    'Preheat oven to 200°C.',
    'Mix olive oil, garlic, lemon juice and zest, rosemary, thyme, salt, and pepper.',
    'Toss potatoes in half the mixture and place on a roasting tray. Roast for 15 minutes.',
    'Coat chicken in remaining mixture. Add to the tray and roast for a further 22–25 minutes.',
    'Rest the chicken for 5 minutes before serving.',
  ],
  imageUrl: '/images/recipes/lemon-herb-chicken.webp',
}

const vegChickpeaCurry: LibraryMeal = {
  id: 'veg-chickpea-curry',
  name: 'Vegetable & Chickpea Curry',
  emoji: '🍲',
  mealType: 'dinner',
  calories: 420,
  proteinG: 18,
  prepMinutes: 30,
  costGBP: 2.80,
  tags: ['vegetarian', 'high-fibre', 'batch-cook', 'budget-friendly', 'under-500-kcal', 'ManvFat-friendly'],
  description: 'A satisfying meat-free curry that is cheap, healthy, and freezes brilliantly.',
  ingredients: [
    '400g tin chickpeas, drained',
    '400g tin chopped tomatoes',
    '1 tin light coconut milk',
    '1 onion, diced',
    '1 sweet potato, cubed',
    '2 tbsp medium curry powder',
    '2 garlic cloves',
    '1 tbsp fresh ginger, grated',
  ],
  steps: [
    'Fry onion, garlic, and ginger in oil for 5 minutes.',
    'Add curry powder and cook for 1 minute.',
    'Add sweet potato, chickpeas, tomatoes, and coconut milk.',
    'Simmer for 20–25 minutes until sweet potato is tender.',
    'Season well and serve with basmati rice or naan.',
  ],
  imageUrl: '/images/recipes/chickpea-curry.webp',
}

// ─── SNACKS (5) ───────────────────────────────────────────────────────────────

const appleWithPeanutButter: LibraryMeal = {
  id: 'apple-peanut-butter',
  name: 'Apple with Peanut Butter',
  emoji: '🍎',
  mealType: 'snack',
  calories: 210,
  proteinG: 5,
  prepMinutes: 2,
  costGBP: 0.70,
  tags: ['healthy-fats', 'quick', 'under-500-kcal', 'ManvFat-friendly'],
  description: 'The classic snack combo. Sweet apple with creamy peanut butter keeps hunger at bay.',
  ingredients: [
    '1 large apple',
    '2 tbsp natural peanut butter (no added sugar)',
  ],
  steps: [
    'Core and slice the apple into wedges.',
    'Serve with peanut butter on the side for dipping.',
  ],
  imageUrl: '/images/recipes/apple-peanut-butter.webp',
}

const cottageCheeseCucumber: LibraryMeal = {
  id: 'cottage-cheese-cucumber',
  name: 'Cottage Cheese with Cucumber',
  emoji: '🧀',
  mealType: 'snack',
  calories: 130,
  proteinG: 16,
  prepMinutes: 3,
  costGBP: 0.80,
  tags: ['high-protein', 'low-carb', 'quick', 'under-500-kcal', 'ManvFat-friendly'],
  description: 'High protein, low calorie, and surprisingly filling. Perfect mid-afternoon snack.',
  ingredients: [
    '150g cottage cheese',
    '½ cucumber, sliced',
    'Black pepper',
    'Pinch of chilli flakes (optional)',
  ],
  steps: [
    'Slice the cucumber.',
    'Spoon cottage cheese into a bowl.',
    'Season with black pepper and optional chilli flakes.',
    'Serve cucumber on the side for dipping.',
  ],
  imageUrl: '/images/recipes/cottage-cheese-cucumber.webp',
}

const mixedNutsBanana: LibraryMeal = {
  id: 'mixed-nuts-banana',
  name: 'Mixed Nuts & a Banana',
  emoji: '🥜',
  mealType: 'snack',
  calories: 260,
  proteinG: 7,
  prepMinutes: 1,
  costGBP: 0.90,
  tags: ['healthy-fats', 'quick', 'under-500-kcal', 'ManvFat-friendly'],
  description: 'A nutrient-dense combination of natural sugars and healthy fats. Great before or after a workout.',
  ingredients: [
    '30g mixed nuts (almonds, cashews, walnuts)',
    '1 banana',
  ],
  steps: [
    'Measure nuts into a small bag or bowl.',
    'Eat alongside the banana.',
  ],
  imageUrl: '/images/recipes/mixed-nuts-banana.webp',
}

const riceCakesHummus: LibraryMeal = {
  id: 'rice-cakes-hummus',
  name: 'Rice Cakes with Hummus',
  emoji: '🫓',
  mealType: 'snack',
  calories: 160,
  proteinG: 6,
  prepMinutes: 2,
  costGBP: 0.75,
  tags: ['vegetarian', 'quick', 'low-calorie', 'under-500-kcal'],
  description: 'Light and crunchy rice cakes with creamy hummus. One of the best low-calorie fillers.',
  ingredients: [
    '3 plain rice cakes',
    '60g hummus',
    'Sliced cucumber or red pepper (optional)',
  ],
  steps: [
    'Spread hummus generously on each rice cake.',
    'Top with sliced cucumber or red pepper if using.',
    'Eat immediately.',
  ],
  imageUrl: '/images/recipes/rice-cakes-hummus.webp',
}

const boiledEggs: LibraryMeal = {
  id: 'boiled-eggs',
  name: 'Boiled Eggs',
  emoji: '🥚',
  mealType: 'snack',
  calories: 155,
  proteinG: 13,
  prepMinutes: 10,
  costGBP: 0.60,
  tags: ['high-protein', 'batch-cook', 'budget-friendly', 'under-500-kcal', 'ManvFat-friendly'],
  description: 'The most portable high-protein snack there is. Batch cook six at the start of the week.',
  ingredients: [
    '2 eggs',
    'Pinch of sea salt',
  ],
  steps: [
    'Bring a small pan of water to the boil.',
    'Lower eggs in gently on a spoon.',
    'Boil for 7 minutes for a set yolk, or 6 minutes for slightly jammy.',
    'Cool in cold water for 2 minutes before peeling.',
  ],
  imageUrl: '/images/recipes/boiled-eggs.webp',
}

// ─── BREAKFAST ADDITIONS ──────────────────────────────────────────────────────

const breakfastBurrito: LibraryMeal = {
  id: 'breakfast-burrito',
  name: 'Breakfast Burrito',
  emoji: '🌯',
  mealType: 'breakfast',
  calories: 480,
  proteinG: 32,
  prepMinutes: 15,
  costGBP: 1.80,
  tags: ['high-protein', 'quick', 'ManvFat-friendly'],
  description: 'Scrambled eggs, bacon and beans wrapped in a warm tortilla. Proper fuel before a busy morning.',
  ingredients: [
    '2 large eggs',
    '2 rashers of lean back bacon',
    '3 tbsp tinned baked beans',
    '1 large flour tortilla',
    '30g reduced-fat cheddar, grated',
    'Splash of hot sauce (optional)',
  ],
  steps: [
    'Grill or dry-fry the bacon until crispy. Chop into small pieces.',
    'Scramble the eggs in a non-stick pan over medium heat. Remove from heat while still slightly soft.',
    'Warm the beans in a small pan or microwave for 60 seconds.',
    'Warm the tortilla in a dry pan for 30 seconds each side.',
    'Lay eggs, bacon, beans and cheese in the centre of the tortilla.',
    'Add a dash of hot sauce if using, then fold in the sides and roll tightly.',
  ],
}

const appleCrumbleOvernightOats: LibraryMeal = {
  id: 'apple-crumble-overnight-oats',
  name: 'Apple Crumble Overnight Oats',
  emoji: '🍎',
  mealType: 'breakfast',
  calories: 360,
  proteinG: 15,
  prepMinutes: 5,
  costGBP: 0.85,
  tags: ['batch-cook', 'high-fibre', 'under-500-kcal', 'ManvFat-friendly'],
  description: 'Tastes like pudding. Costs less than a pound. Mix it the night before and grab it on the way out.',
  ingredients: [
    '80g rolled oats',
    '200ml semi-skimmed milk',
    '100g Greek yoghurt',
    '1 apple, grated',
    '1 tsp cinnamon',
    '1 tsp honey',
    '1 tbsp crushed walnuts or granola',
  ],
  steps: [
    'Stir oats, milk, yoghurt, grated apple and cinnamon together in a jar or container.',
    'Seal and refrigerate overnight.',
    'In the morning, top with crushed walnuts or granola and a drizzle of honey.',
  ],
}

const eggBhurji: LibraryMeal = {
  id: 'egg-bhurji',
  name: 'Spiced Scrambled Eggs',
  emoji: '🍳',
  mealType: 'breakfast',
  calories: 350,
  proteinG: 26,
  prepMinutes: 10,
  costGBP: 1.10,
  tags: ['high-protein', 'quick', 'under-500-kcal', 'ManvFat-friendly'],
  description: 'Scrambled eggs with onion, tomato and a bit of spice. A cracking change from plain eggs on toast.',
  ingredients: [
    '3 eggs',
    '½ onion, finely diced',
    '1 tomato, diced',
    '½ tsp cumin',
    '¼ tsp turmeric',
    '¼ tsp chilli flakes',
    '1 tsp oil',
    'Small handful of fresh coriander (optional)',
    '1 slice wholemeal toast',
  ],
  steps: [
    'Heat oil in a non-stick pan. Fry onion for 2–3 minutes until softened.',
    'Add tomato, cumin, turmeric and chilli. Cook for another minute.',
    'Beat eggs and pour in. Stir constantly over medium heat.',
    'Remove from heat while eggs are still a little soft.',
    'Scatter over fresh coriander if using. Serve with toast.',
  ],
}

const cleanSheetSkillet: LibraryMeal = {
  id: 'clean-sheet-skillet',
  name: 'Clean Sheet Skillet',
  emoji: '🥚',
  mealType: 'breakfast',
  calories: 430,
  proteinG: 34,
  prepMinutes: 12,
  costGBP: 1.50,
  tags: ['high-protein', 'one-pan', 'ManvFat-friendly'],
  description: 'Eggs baked over spinach, mushrooms and cherry tomatoes in one pan. All the nutrients, barely any washing up.',
  ingredients: [
    '3 eggs',
    '80g chestnut mushrooms, sliced',
    '50g baby spinach',
    '6 cherry tomatoes, halved',
    '1 tsp oil',
    'Salt and black pepper',
    '1 slice wholemeal toast',
  ],
  steps: [
    'Heat oil in a small oven-proof frying pan over medium heat.',
    'Fry mushrooms for 3 minutes until golden. Add tomatoes and spinach, cook until wilted.',
    'Make three small wells in the veg and crack an egg into each.',
    'Cover with a lid or foil and cook on low for 4–5 minutes until whites are set.',
    'Season with salt and pepper. Serve straight from the pan with toast.',
  ],
}

const pbBananaToast: LibraryMeal = {
  id: 'pb-banana-toast',
  name: 'Peanut Butter & Banana Toast',
  emoji: '🍞',
  mealType: 'breakfast',
  calories: 400,
  proteinG: 14,
  prepMinutes: 5,
  costGBP: 0.70,
  tags: ['quick', 'budget-friendly', 'under-500-kcal', 'ManvFat-friendly'],
  description: 'Fast, filling and genuinely tasty. The banana keeps energy levels steady all morning.',
  ingredients: [
    '2 slices wholemeal bread',
    '2 tbsp peanut butter (no added sugar)',
    '1 banana, sliced',
    'Pinch of cinnamon',
  ],
  steps: [
    'Toast the bread.',
    'Spread a generous tablespoon of peanut butter on each slice.',
    'Layer banana slices on top.',
    'Dust with cinnamon and eat immediately.',
  ],
}

const bananaProteinPancakes: LibraryMeal = {
  id: 'banana-protein-pancakes',
  name: 'Banana Protein Pancakes',
  emoji: '🥞',
  mealType: 'breakfast',
  calories: 380,
  proteinG: 28,
  prepMinutes: 15,
  costGBP: 1.20,
  tags: ['high-protein', 'ManvFat-friendly', 'under-500-kcal'],
  description: 'Three-ingredient pancakes that actually taste good. High in protein, no flour needed.',
  ingredients: [
    '1 ripe banana',
    '2 eggs',
    '30g vanilla or unflavoured protein powder',
    '1 tsp oil',
    '100g Greek yoghurt and a handful of berries to serve',
  ],
  steps: [
    'Mash the banana thoroughly in a bowl.',
    'Beat in the eggs and protein powder until smooth. The batter will be thin.',
    'Heat a little oil in a non-stick pan over medium-low heat.',
    'Pour in small rounds of batter (about 2 tbsp each). Cook for 2 minutes per side.',
    'Serve with Greek yoghurt and berries.',
  ],
}

// ─── LUNCH ADDITIONS ──────────────────────────────────────────────────────────

const ploughmansBox: LibraryMeal = {
  id: 'ploughmans-box',
  name: "Ploughman's Lunchbox",
  emoji: '🧀',
  mealType: 'lunch',
  calories: 420,
  proteinG: 22,
  prepMinutes: 5,
  costGBP: 2.20,
  tags: ['no-cook', 'batch-cook', 'ManvFat-friendly'],
  description: 'A proper British classic that needs zero cooking. Quick to assemble, easy to take to work.',
  ingredients: [
    '60g reduced-fat cheddar',
    '2 slices wholemeal bread or 4 oatcakes',
    '2 slices lean ham',
    '1 hard-boiled egg',
    '1 tbsp pickle (Branston)',
    'Celery sticks and cherry tomatoes to fill the box',
  ],
  steps: [
    'Hard-boil the egg in advance and refrigerate until needed.',
    'Pack cheese, ham, egg, pickle and veg into a container.',
    'Add bread or oatcakes in a separate bag to keep them from going soggy.',
    'Eat at room temperature.',
  ],
}

const tunaMeltToastie: LibraryMeal = {
  id: 'tuna-melt-toastie',
  name: 'Tuna Melt Toastie',
  emoji: '🥪',
  mealType: 'lunch',
  calories: 450,
  proteinG: 34,
  prepMinutes: 10,
  costGBP: 1.60,
  tags: ['high-protein', 'quick', 'ManvFat-friendly'],
  description: 'Melted cheese on tuna mayo in a toastie. One of the most satisfying lunches for under £2.',
  ingredients: [
    '1 tin tuna in spring water, drained',
    '1 tbsp light mayonnaise',
    '2 slices wholemeal bread',
    '40g reduced-fat cheddar, grated',
    '½ tsp Worcestershire sauce',
    'Sliced tomato (optional)',
  ],
  steps: [
    'Mix tuna, mayo and Worcestershire sauce together.',
    'Spread onto one slice of bread. Top with tomato (if using) and cheese.',
    'Put the second slice on top.',
    'Toast in a sandwich press, dry frying pan or under the grill until golden and melted.',
  ],
}

const cajunChickenRiceBowl: LibraryMeal = {
  id: 'cajun-chicken-rice-bowl',
  name: 'Cajun Chicken Rice Bowl',
  emoji: '🍚',
  mealType: 'lunch',
  calories: 490,
  proteinG: 38,
  prepMinutes: 20,
  costGBP: 2.20,
  tags: ['high-protein', 'batch-cook', 'ManvFat-friendly'],
  description: 'Spiced chicken over rice with sweetcorn and peppers. Batch cook the rice on Sunday and this takes ten minutes all week.',
  ingredients: [
    '150g chicken breast, diced',
    '1 tsp Cajun seasoning',
    '150g cooked brown rice',
    '50g tinned sweetcorn',
    '½ red pepper, sliced',
    '1 tsp oil',
    'Squeeze of lime (optional)',
  ],
  steps: [
    'Toss chicken with Cajun seasoning.',
    'Heat oil in a frying pan over high heat. Cook chicken for 6–8 minutes until cooked through.',
    'Add pepper strips to the pan for the last 2 minutes.',
    'Serve over rice with sweetcorn. Squeeze lime over the top if using.',
  ],
}

const bigLadChilliPot: LibraryMeal = {
  id: 'big-lad-chilli-pot',
  name: 'Big Lad Chilli Pot',
  emoji: '🍲',
  mealType: 'lunch',
  calories: 460,
  proteinG: 32,
  prepMinutes: 15,
  costGBP: 1.80,
  tags: ['high-protein', 'batch-cook', 'budget-friendly', 'ManvFat-friendly'],
  description: 'Tinned kidney beans and mince with chilli spices. Cheap, filling and ridiculously easy to batch cook.',
  ingredients: [
    '150g lean beef mince (5% fat)',
    '1 tin kidney beans, drained',
    '1 tin chopped tomatoes',
    '1 tsp cumin',
    '1 tsp smoked paprika',
    '½ tsp chilli powder',
    '1 small onion, diced',
    '1 tsp oil',
  ],
  steps: [
    'Heat oil in a pan. Fry onion for 3 minutes. Add mince and brown for 5 minutes.',
    'Stir in cumin, paprika and chilli powder. Cook for 1 minute.',
    'Add tomatoes and kidney beans. Simmer for 10 minutes, stirring occasionally.',
    'Season with salt and pepper. Serve as is or over rice.',
  ],
}

const srirachaChickenSlawWrap: LibraryMeal = {
  id: 'sriracha-chicken-slaw-wrap',
  name: 'Sriracha Chicken Slaw Wrap',
  emoji: '🌯',
  mealType: 'lunch',
  calories: 440,
  proteinG: 33,
  prepMinutes: 10,
  costGBP: 2.10,
  tags: ['high-protein', 'quick', 'ManvFat-friendly'],
  description: 'Shredded chicken with crunchy slaw and a kick of sriracha. Far better than anything from a meal-deal fridge.',
  ingredients: [
    '150g cooked chicken breast, shredded',
    '2 large flour tortillas',
    '60g coleslaw (shop-bought)',
    '1 tbsp light mayo',
    '1 tsp sriracha sauce',
    'Handful of iceberg lettuce',
  ],
  steps: [
    'Mix shredded chicken with mayo and sriracha.',
    'Warm tortillas for 30 seconds in a dry pan.',
    'Lay lettuce and coleslaw along the centre of each tortilla.',
    'Top with the chicken mixture, roll tightly and cut in half.',
  ],
}

const coronationChickenChickpeaSalad: LibraryMeal = {
  id: 'coronation-chicken-chickpea-salad',
  name: 'Coronation Chicken & Chickpea Salad',
  emoji: '🥗',
  mealType: 'lunch',
  calories: 410,
  proteinG: 30,
  prepMinutes: 10,
  costGBP: 2.00,
  tags: ['high-protein', 'no-cook', 'ManvFat-friendly'],
  description: 'Curried chicken and chickpeas on a bed of leaves. Sounds fancy, takes ten minutes and keeps well in the fridge.',
  ingredients: [
    '150g cooked chicken breast, diced',
    '100g tinned chickpeas, drained',
    '2 tbsp light mayo',
    '1 tsp mild curry powder',
    '1 tbsp mango chutney',
    'Handful of mixed leaves',
    'Sliced cucumber',
  ],
  steps: [
    'Mix mayo, curry powder and mango chutney in a bowl.',
    'Add chicken and chickpeas. Stir to coat.',
    'Serve over mixed leaves with sliced cucumber.',
    'Keeps in the fridge for up to two days.',
  ],
}

// ─── DINNER ADDITIONS ─────────────────────────────────────────────────────────

const beefBurgerWedges: LibraryMeal = {
  id: 'beef-burger-wedges',
  name: 'Lean Beef Burger & Wedges',
  emoji: '🍔',
  mealType: 'dinner',
  calories: 550,
  proteinG: 38,
  prepMinutes: 30,
  costGBP: 2.80,
  tags: ['high-protein', 'ManvFat-friendly', 'family-friendly'],
  description: 'A proper homemade burger with oven wedges. Lean mince keeps the calories under control without sacrificing any of the taste.',
  ingredients: [
    '200g lean beef mince (5% fat)',
    '2 burger buns (wholemeal if available)',
    '2 medium potatoes, cut into wedges',
    '1 tsp smoked paprika',
    '1 tsp oil',
    'Lettuce, tomato, sliced onion',
    '1 tbsp ketchup or mustard',
    'Salt and black pepper',
  ],
  steps: [
    'Preheat oven to 200°C. Toss potato wedges in oil and paprika. Spread on a baking tray.',
    'Bake wedges for 25–30 minutes, turning halfway, until golden.',
    'Shape mince into two patties. Season both sides with salt and pepper.',
    'Cook patties in a hot dry frying pan for 4–5 minutes per side.',
    'Serve in buns with lettuce, tomato and onion. Add sauce to taste.',
  ],
}

const sweetChilliChickenStirFry: LibraryMeal = {
  id: 'sweet-chilli-chicken-stir-fry',
  name: 'Sweet Chilli Chicken Stir-fry',
  emoji: '🥡',
  mealType: 'dinner',
  calories: 480,
  proteinG: 36,
  prepMinutes: 15,
  costGBP: 2.20,
  tags: ['high-protein', 'quick', 'ManvFat-friendly'],
  description: 'A takeaway-quality stir-fry in 15 minutes. Sweet chilli sauce does the heavy lifting on flavour.',
  ingredients: [
    '200g chicken breast, sliced thin',
    '1 bag stir-fry veg (300g)',
    '3 tbsp sweet chilli sauce',
    '1 tbsp low-sodium soy sauce',
    '1 tsp sesame oil',
    '150g cooked egg noodles or rice',
    '1 tsp oil',
  ],
  steps: [
    'Heat oil in a wok or large frying pan over high heat.',
    'Add chicken. Stir-fry for 5–6 minutes until cooked through. Remove and set aside.',
    'Add veg to the hot pan. Stir-fry for 3 minutes.',
    'Return chicken. Add sweet chilli sauce, soy sauce and sesame oil. Toss everything together.',
    'Serve over noodles or rice.',
  ],
}

const periPeriChickenWedges: LibraryMeal = {
  id: 'peri-peri-chicken-wedges',
  name: 'Peri-Peri Chicken & Wedges',
  emoji: '🍗',
  mealType: 'dinner',
  calories: 510,
  proteinG: 40,
  prepMinutes: 30,
  costGBP: 2.50,
  tags: ['high-protein', 'family-friendly', 'ManvFat-friendly'],
  description: 'Marinated chicken thighs with crispy oven wedges. Nandos-flavour without the £14 price tag.',
  ingredients: [
    '2 chicken thigh fillets (skinless)',
    '2 medium potatoes, cut into wedges',
    '2 tbsp peri-peri sauce (from a jar)',
    '1 tsp oil',
    '½ lemon',
    'Corn on the cob or side salad to serve',
  ],
  steps: [
    'Preheat oven to 200°C.',
    'Toss wedges in oil, spread on a baking tray and bake for 25–30 minutes.',
    'Coat chicken thighs in peri-peri sauce. Place on a second baking tray.',
    'Bake chicken for 25 minutes until cooked through with charred edges.',
    'Squeeze lemon over both. Serve with a side of corn or salad.',
  ],
}

const sausagePepperBake: LibraryMeal = {
  id: 'sausage-pepper-bake',
  name: 'Sausage & Pepper Tray Bake',
  emoji: '🌶️',
  mealType: 'dinner',
  calories: 490,
  proteinG: 28,
  prepMinutes: 30,
  costGBP: 2.40,
  tags: ['one-pan', 'family-friendly', 'batch-cook', 'ManvFat-friendly'],
  description: 'Everything in one tray. Lean sausages, peppers and onions roasted together. Barely any effort, barely any washing up.',
  ingredients: [
    '4 reduced-fat pork sausages',
    '2 mixed peppers, sliced',
    '1 large red onion, cut into wedges',
    '2 medium potatoes, diced',
    '1 tsp smoked paprika',
    '1 tsp mixed herbs',
    '1 tbsp olive oil',
  ],
  steps: [
    'Preheat oven to 200°C.',
    'Spread potatoes, peppers and onion on a large baking tray. Drizzle with oil, scatter over paprika and herbs.',
    'Nestle sausages among the veg.',
    'Bake for 30 minutes, turning everything halfway through, until sausages are browned and potatoes are tender.',
  ],
}

const salmonFishcakesPeas: LibraryMeal = {
  id: 'salmon-fishcakes-peas',
  name: 'Salmon Fishcakes & Peas',
  emoji: '🐟',
  mealType: 'dinner',
  calories: 470,
  proteinG: 32,
  prepMinutes: 25,
  costGBP: 2.60,
  tags: ['high-protein', 'ManvFat-friendly'],
  description: 'Homemade fishcakes from tinned salmon and mash. Quick to make and far cheaper than the supermarket versions.',
  ingredients: [
    '1 tin salmon (213g), drained',
    '2 medium potatoes, boiled and mashed',
    '1 tbsp light mayo',
    '1 tsp Dijon mustard',
    '2 spring onions, sliced',
    '1 tbsp plain flour',
    '100g frozen peas',
    '1 tsp oil',
  ],
  steps: [
    'Mix salmon, mash, mayo, mustard and spring onions together. Season well.',
    'Shape into four patties. Dust lightly with flour.',
    'Heat oil in a non-stick frying pan over medium heat. Cook fishcakes for 4 minutes per side until golden.',
    'Cook peas in boiling water for 3 minutes. Serve alongside.',
  ],
}

const beefBroccoliBlackBean: LibraryMeal = {
  id: 'beef-broccoli-black-bean',
  name: 'Beef, Broccoli & Black Bean',
  emoji: '🥩',
  mealType: 'dinner',
  calories: 460,
  proteinG: 38,
  prepMinutes: 20,
  costGBP: 2.50,
  tags: ['high-protein', 'quick', 'ManvFat-friendly'],
  description: 'A classic Chinese-inspired stir-fry with tender beef and crispy broccoli. Proper takeaway flavours at a fraction of the cost.',
  ingredients: [
    '200g lean beef strips or rump steak, sliced thin',
    '200g broccoli florets',
    '2 tbsp black bean sauce',
    '1 tbsp low-sodium soy sauce',
    '1 tsp sesame oil',
    '2 garlic cloves, minced',
    '150g cooked rice',
    '1 tsp oil',
  ],
  steps: [
    'Heat oil in a wok over very high heat. Add beef strips and cook for 2–3 minutes. Remove and set aside.',
    'Add broccoli and garlic to the hot wok. Stir-fry for 3 minutes.',
    'Return beef. Add black bean sauce, soy sauce and sesame oil. Toss together for 1 minute.',
    'Serve over rice.',
  ],
}

const bbqPulledChickenBaps: LibraryMeal = {
  id: 'bbq-pulled-chicken-baps',
  name: 'BBQ Pulled Chicken Baps',
  emoji: '🍗',
  mealType: 'dinner',
  calories: 500,
  proteinG: 40,
  prepMinutes: 20,
  costGBP: 2.20,
  tags: ['high-protein', 'quick', 'family-friendly', 'ManvFat-friendly'],
  description: 'Tender pulled chicken in smoky BBQ sauce. Serve in a bap with coleslaw. Faster than ordering a takeaway.',
  ingredients: [
    '2 chicken breast fillets',
    '3 tbsp BBQ sauce',
    '1 tsp smoked paprika',
    '2 burger baps',
    '60g coleslaw',
    '1 tsp oil',
  ],
  steps: [
    'Slice chicken breasts thin, or use the flat of a rolling pin to bash them out to even thickness.',
    'Rub with paprika. Heat oil in a frying pan over high heat. Cook chicken for 5–6 minutes per side.',
    'Remove from heat and shred with two forks.',
    'Return shredded chicken to the pan with BBQ sauce. Toss over low heat for 1–2 minutes.',
    'Pile into baps with coleslaw.',
  ],
}

const chickenCheeseQuesadilla: LibraryMeal = {
  id: 'chicken-cheese-quesadilla',
  name: 'Chicken & Cheese Quesadilla',
  emoji: '🫓',
  mealType: 'dinner',
  calories: 490,
  proteinG: 38,
  prepMinutes: 15,
  costGBP: 2.20,
  tags: ['high-protein', 'quick', 'family-friendly', 'ManvFat-friendly'],
  description: 'Crispy tortilla filled with chicken, cheese and peppers. Kids love them. Ready in 15 minutes flat.',
  ingredients: [
    '150g cooked chicken breast, shredded',
    '2 large flour tortillas',
    '60g reduced-fat cheddar, grated',
    '½ red pepper, finely diced',
    '½ tsp smoked paprika',
    '1 tsp oil',
    'Salsa or Greek yoghurt to serve',
  ],
  steps: [
    'Mix shredded chicken with pepper and paprika.',
    'Lay one tortilla flat. Cover half with chicken mixture and cheese.',
    'Fold the tortilla over to make a half-moon shape.',
    'Heat oil in a large frying pan. Cook quesadilla for 2–3 minutes per side until golden and crispy.',
    'Cut into wedges and serve with salsa or a dollop of Greek yoghurt.',
  ],
}

// ─── SNACK ADDITIONS ──────────────────────────────────────────────────────────

const srirachaBoiledEggs: LibraryMeal = {
  id: 'sriracha-boiled-eggs',
  name: 'Sriracha Boiled Eggs',
  emoji: '🥚',
  mealType: 'snack',
  calories: 170,
  proteinG: 14,
  prepMinutes: 10,
  costGBP: 0.75,
  tags: ['high-protein', 'batch-cook', 'budget-friendly', 'under-500-kcal'],
  description: 'Boiled eggs with a drizzle of sriracha. A spicy upgrade on the classic batch-cook snack.',
  ingredients: [
    '2 eggs',
    '½ tsp sriracha sauce',
    'Pinch of sea salt',
    'Pinch of sesame seeds (optional)',
  ],
  steps: [
    'Bring a small pan of water to the boil.',
    'Lower eggs in gently and boil for 7 minutes for a set yolk.',
    'Cool in cold water for 2 minutes, then peel.',
    'Halve and top each half with a small drizzle of sriracha. Scatter sesame seeds if using.',
  ],
}

const spicedRoastedChickpeas: LibraryMeal = {
  id: 'spiced-roasted-chickpeas',
  name: 'Spiced Roasted Chickpeas',
  emoji: '🫘',
  mealType: 'snack',
  calories: 150,
  proteinG: 8,
  prepMinutes: 30,
  costGBP: 0.50,
  tags: ['batch-cook', 'budget-friendly', 'high-fibre', 'under-500-kcal'],
  description: 'Crunchy, moreish and miles better than crisps. Make a big batch and keep in a jar for the week.',
  ingredients: [
    '1 tin chickpeas, drained and rinsed',
    '1 tsp olive oil',
    '1 tsp smoked paprika',
    '½ tsp cumin',
    '¼ tsp salt',
  ],
  steps: [
    'Preheat oven to 200°C. Dry chickpeas thoroughly with a clean tea towel.',
    'Toss with oil, paprika, cumin and salt.',
    'Spread on a baking tray in a single layer.',
    'Roast for 25–30 minutes until golden and crispy. They will firm up further as they cool.',
    'Store in an open container at room temperature for up to five days.',
  ],
}

const saltPepperEdamame: LibraryMeal = {
  id: 'salt-pepper-edamame',
  name: 'Salt & Pepper Edamame',
  emoji: '🫛',
  mealType: 'snack',
  calories: 120,
  proteinG: 11,
  prepMinutes: 5,
  costGBP: 0.80,
  tags: ['high-protein', 'quick', 'budget-friendly', 'under-500-kcal'],
  description: 'Frozen edamame defrosted in two minutes. One of the best high-protein snacks going and most supermarkets stock them.',
  ingredients: [
    '150g frozen edamame (in pods)',
    '¼ tsp flaky sea salt',
    '¼ tsp black pepper',
    '½ tsp sesame oil (optional)',
  ],
  steps: [
    'Cook edamame according to pack instructions (usually 3 minutes in boiling water, or 2 minutes in the microwave).',
    'Drain and toss with salt, pepper and sesame oil if using.',
    'Eat by squeezing the beans out of the pods into your mouth.',
  ],
}

const skyrBerryPot: LibraryMeal = {
  id: 'skyr-berry-pot',
  name: 'Skyr Berry Pot',
  emoji: '🫙',
  mealType: 'snack',
  calories: 180,
  proteinG: 18,
  prepMinutes: 2,
  costGBP: 1.20,
  tags: ['high-protein', 'quick', 'under-500-kcal', 'ManvFat-friendly'],
  description: "Skyr is Iceland's answer to Greek yoghurt. More protein per serving, slightly milder taste. Top with berries and that's your afternoon snack sorted.",
  ingredients: [
    '170g plain skyr (or thick Greek yoghurt)',
    '80g mixed berries (fresh or defrosted frozen)',
    '1 tsp honey',
    '1 tbsp granola (optional)',
  ],
  steps: [
    'Spoon skyr into a bowl or travel pot.',
    'Top with berries and drizzle over honey.',
    'Add granola for extra crunch if using. Eat straight away or refrigerate for up to four hours.',
  ],
}

const hamMozzarellaRollUps: LibraryMeal = {
  id: 'ham-mozzarella-roll-ups',
  name: 'Ham & Mozzarella Roll-Ups',
  emoji: '🧀',
  mealType: 'snack',
  calories: 160,
  proteinG: 17,
  prepMinutes: 3,
  costGBP: 1.30,
  tags: ['high-protein', 'no-cook', 'quick', 'under-500-kcal'],
  description: 'Sliced ham wrapped around mozzarella sticks. Tastes like proper food, takes 3 minutes and keeps in the fridge all week.',
  ingredients: [
    '4 slices lean cooked ham',
    '2 mozzarella string cheese sticks (or 60g fresh mozzarella)',
    'A few basil leaves or sliced sun-dried tomato (optional)',
  ],
  steps: [
    'Lay each ham slice flat.',
    'Place half a mozzarella stick (or a chunk of fresh mozzarella) at one edge.',
    'Add basil or sun-dried tomato if using.',
    'Roll the ham tightly around the filling. Secure with a cocktail stick if needed.',
    'Refrigerate until ready to eat.',
  ],
}

// ─── EXPORTS ──────────────────────────────────────────────────────────────────

export const mealLibrary: LibraryMeal[] = [
  // Breakfast
  overnightOats,
  scrambledEggsToast,
  greekYoghurtParfait,
  proteinSmoothie,
  avocadoEggsToast,
  bananaPorridge,
  breakfastBurrito,
  appleCrumbleOvernightOats,
  eggBhurji,
  cleanSheetSkillet,
  pbBananaToast,
  bananaProteinPancakes,
  // Lunch
  chickenCaesarWrap,
  tunaJacketPotato,
  prawnStirFryNoodles,
  lentilSoup,
  greekSaladChicken,
  ploughmansBox,
  tunaMeltToastie,
  cajunChickenRiceBowl,
  bigLadChilliPot,
  srirachaChickenSlawWrap,
  coronationChickenChickpeaSalad,
  // Dinner
  turkeyBolognese,
  bakedSalmonRoastedVeg,
  chickenTikkaMasala,
  beefChilli,
  prawnVegStirFry,
  cottagePieSweetPotato,
  chickenChorizo,
  lemonHerbChicken,
  vegChickpeaCurry,
  beefBurgerWedges,
  sweetChilliChickenStirFry,
  periPeriChickenWedges,
  sausagePepperBake,
  salmonFishcakesPeas,
  beefBroccoliBlackBean,
  bbqPulledChickenBaps,
  chickenCheeseQuesadilla,
  // Snack
  appleWithPeanutButter,
  cottageCheeseCucumber,
  mixedNutsBanana,
  riceCakesHummus,
  boiledEggs,
  srirachaBoiledEggs,
  spicedRoastedChickpeas,
  saltPepperEdamame,
  skyrBerryPot,
  hamMozzarellaRollUps,
]

export const getMealsByType = (type: LibraryMeal['mealType']) =>
  mealLibrary.filter((m) => m.mealType === type)

export const mealTypeLabel: Record<LibraryMeal['mealType'], string> = {
  breakfast: 'Breakfast',
  lunch: 'Lunch',
  dinner: 'Dinner',
  snack: 'Snack',
}
