export type LibraryMeal = {
  id: string
  name: string
  emoji: string
  mealType: 'breakfast' | 'lunch' | 'dinner' | 'snack'
  calories: number
  proteinG: number
  prepMinutes: number
  costGBP: number
  tags: string[]
  description: string
  ingredients: string[]
  steps: string[]
}

export const mealLibrary: LibraryMeal[] = [
  // ─── BREAKFAST ──────────────────────────────────────────────────────────────
  {
    id: 'overnight-oats',
    name: 'Overnight Oats with Berries',
    emoji: '🫙',
    mealType: 'breakfast',
    calories: 350,
    proteinG: 14,
    prepMinutes: 5,
    costGBP: 0.90,
    tags: ['High fibre', 'Meal prep', 'No cook'],
    description: 'Creamy oats soaked overnight with mixed berries and a hit of protein. Grab and go.',
    ingredients: ['80g rolled oats', '200ml semi-skimmed milk', '100g Greek yoghurt', '1 tbsp chia seeds', '100g mixed berries', '1 tsp honey'],
    steps: [
      'Add oats, milk, yoghurt, and chia seeds to a jar or container. Stir well.',
      'Cover and refrigerate overnight (or at least 4 hours).',
      'In the morning, top with berries and drizzle with honey.',
      'Add a splash more milk if you prefer a looser consistency.',
    ],
  },
  {
    id: 'scrambled-eggs-toast',
    name: 'Scrambled Eggs & Wholemeal Toast',
    emoji: '🍳',
    mealType: 'breakfast',
    calories: 400,
    proteinG: 28,
    prepMinutes: 10,
    costGBP: 1.20,
    tags: ['High protein', 'Quick'],
    description: 'Fluffy scrambled eggs on seeded wholemeal toast — simple, filling, and packed with protein.',
    ingredients: ['3 eggs', '2 slices wholemeal bread', '1 tbsp butter', '30ml semi-skimmed milk', 'Salt and black pepper', 'Handful of spinach (optional)'],
    steps: [
      'Crack eggs into a bowl, add milk, season with salt and pepper, and whisk.',
      'Melt butter in a non-stick pan over low heat.',
      'Pour in eggs. Stir slowly and continuously with a spatula until just set — don\'t overcook.',
      'Toast the bread. Wilt spinach in the pan for 30 seconds if using.',
      'Serve eggs immediately on toast.',
    ],
  },
  {
    id: 'greek-yoghurt-parfait',
    name: 'Greek Yoghurt Parfait',
    emoji: '🍓',
    mealType: 'breakfast',
    calories: 310,
    proteinG: 20,
    prepMinutes: 5,
    costGBP: 1.60,
    tags: ['High protein', 'No cook', 'Quick'],
    description: 'Layers of thick Greek yoghurt, granola, and fresh fruit. Ready in 5 minutes.',
    ingredients: ['200g full-fat Greek yoghurt', '30g low-sugar granola', '1 banana sliced', '80g strawberries', '1 tsp honey'],
    steps: [
      'Spoon half the yoghurt into a glass or bowl.',
      'Add half the granola and banana.',
      'Layer the remaining yoghurt on top.',
      'Top with strawberries, remaining granola, and a drizzle of honey.',
    ],
  },
  {
    id: 'protein-banana-smoothie',
    name: 'Banana Protein Smoothie',
    emoji: '🥤',
    mealType: 'breakfast',
    calories: 370,
    proteinG: 30,
    prepMinutes: 5,
    costGBP: 1.30,
    tags: ['High protein', 'Quick', 'No cook'],
    description: 'A thick, creamy smoothie that keeps you full until lunch. Great post-workout too.',
    ingredients: ['1 banana (frozen is best)', '1 scoop vanilla protein powder', '200ml semi-skimmed milk', '1 tbsp peanut butter', '1 tsp honey', '3–4 ice cubes'],
    steps: [
      'Add all ingredients to a blender.',
      'Blend on high for 30–60 seconds until smooth.',
      'Taste and add more honey if needed.',
      'Drink immediately.',
    ],
  },
  {
    id: 'avocado-eggs-toast',
    name: 'Avocado & Poached Egg Toast',
    emoji: '🥑',
    mealType: 'breakfast',
    calories: 460,
    proteinG: 22,
    prepMinutes: 12,
    costGBP: 2.10,
    tags: ['Healthy fats', 'High protein'],
    description: 'Smashed avocado on sourdough topped with a perfectly poached egg. Weekend treat vibes on a weekday.',
    ingredients: ['2 slices sourdough bread', '1 ripe avocado', '2 eggs', '1 tsp lemon juice', 'Chilli flakes', 'Salt and black pepper'],
    steps: [
      'Toast the sourdough until golden.',
      'Halve the avocado, remove the stone, and scoop into a bowl. Add lemon juice, salt, and pepper. Mash roughly.',
      'Bring a pan of water to a gentle simmer. Add a splash of vinegar.',
      'Crack each egg into a small cup. Swirl the water and slide eggs in. Cook for 3 minutes for a runny yolk.',
      'Spread avocado on toast, top with eggs, and scatter chilli flakes.',
    ],
  },

  // ─── LUNCH ──────────────────────────────────────────────────────────────────
  {
    id: 'tuna-sweetcorn-wrap',
    name: 'Tuna & Sweetcorn Wrap',
    emoji: '🌯',
    mealType: 'lunch',
    calories: 420,
    proteinG: 38,
    prepMinutes: 5,
    costGBP: 1.80,
    tags: ['High protein', 'Quick', 'Meal prep'],
    description: 'A classic high-protein lunch. Quick to assemble and easy to take to work.',
    ingredients: ['1 wholemeal tortilla wrap', '1 tin tuna in water (drained)', '50g sweetcorn', '2 tbsp light mayonnaise', 'Handful of iceberg lettuce', '½ lemon'],
    steps: [
      'Mix drained tuna with sweetcorn, mayo, and a squeeze of lemon. Season with pepper.',
      'Lay the wrap flat. Place lettuce down the centre.',
      'Spoon the tuna mix on top.',
      'Fold in the sides and roll up firmly.',
    ],
  },
  {
    id: 'chicken-caesar-salad',
    name: 'Chicken Caesar Salad',
    emoji: '🥗',
    mealType: 'lunch',
    calories: 390,
    proteinG: 42,
    prepMinutes: 10,
    costGBP: 3.20,
    tags: ['High protein', 'Low carb'],
    description: 'Lean grilled chicken on crisp romaine with a light Caesar dressing. Proper filling.',
    ingredients: ['150g cooked chicken breast (sliced)', '2 large handfuls romaine lettuce', '20g parmesan shavings', '30g croutons', '2 tbsp Caesar dressing', 'Black pepper'],
    steps: [
      'Tear the romaine into bite-sized pieces and place in a large bowl.',
      'Add the sliced chicken, croutons, and parmesan.',
      'Drizzle with Caesar dressing and toss everything together.',
      'Season with black pepper and serve.',
    ],
  },
  {
    id: 'lentil-vegetable-soup',
    name: 'Red Lentil & Vegetable Soup',
    emoji: '🍲',
    mealType: 'lunch',
    calories: 290,
    proteinG: 18,
    prepMinutes: 25,
    costGBP: 1.20,
    tags: ['High fibre', 'Budget friendly', 'Meal prep'],
    description: 'Hearty, filling, and dirt cheap. Make a big batch on Sunday and eat it all week.',
    ingredients: ['150g red lentils', '1 onion (diced)', '2 carrots (diced)', '2 garlic cloves', '400ml vegetable stock', '1 tsp cumin', '1 tsp turmeric', '1 tbsp olive oil'],
    steps: [
      'Heat oil in a large pan. Fry onion and carrots for 5 minutes until softened.',
      'Add garlic, cumin, and turmeric. Cook for 1 minute.',
      'Add lentils and stock. Bring to a boil, then simmer for 15 minutes until lentils are soft.',
      'Blend half the soup for a thicker consistency, or leave chunky.',
      'Season and serve with crusty bread.',
    ],
  },
  {
    id: 'salmon-quinoa-bowl',
    name: 'Salmon & Quinoa Power Bowl',
    emoji: '🐟',
    mealType: 'lunch',
    calories: 490,
    proteinG: 42,
    prepMinutes: 20,
    costGBP: 4.00,
    tags: ['High protein', 'Omega-3', 'Meal prep'],
    description: 'Baked salmon on a bed of quinoa with cucumber, cherry tomatoes, and a lemon drizzle.',
    ingredients: ['150g salmon fillet', '80g quinoa', '½ cucumber (diced)', '100g cherry tomatoes', '1 tbsp olive oil', '½ lemon', 'Fresh dill or parsley'],
    steps: [
      'Cook quinoa according to packet instructions (about 15 minutes).',
      'Season salmon with salt, pepper, and olive oil. Bake at 200°C for 12–15 minutes.',
      'Fluff the quinoa and spread into a bowl.',
      'Top with cucumber, tomatoes, and flaked salmon.',
      'Squeeze lemon over and scatter herbs.',
    ],
  },
  {
    id: 'turkey-avocado-sandwich',
    name: 'Turkey & Avocado Club Sandwich',
    emoji: '🥪',
    mealType: 'lunch',
    calories: 460,
    proteinG: 34,
    prepMinutes: 5,
    costGBP: 2.80,
    tags: ['High protein', 'Quick'],
    description: 'Lean turkey with creamy avocado and crisp salad on wholegrain. Tastes like proper food.',
    ingredients: ['2 slices wholegrain bread', '100g sliced turkey breast', '½ avocado', '2 slices tomato', 'Handful of rocket', '1 tsp Dijon mustard'],
    steps: [
      'Slice the avocado and season with a pinch of salt.',
      'Spread mustard on both slices of bread.',
      'Layer turkey, avocado, tomato, and rocket.',
      'Top with the second slice, press gently, and cut in half.',
    ],
  },

  // ─── DINNER ─────────────────────────────────────────────────────────────────
  {
    id: 'chicken-stir-fry',
    name: 'Chicken & Vegetable Stir-fry',
    emoji: '🥘',
    mealType: 'dinner',
    calories: 430,
    proteinG: 44,
    prepMinutes: 20,
    costGBP: 3.80,
    tags: ['High protein', 'Quick', 'Low fat'],
    description: 'Lean chicken with colourful veg in a savoury soy and ginger sauce. Serve with rice or noodles.',
    ingredients: ['300g chicken breast (sliced)', '1 red pepper', '200g broccoli florets', '1 carrot (julienned)', '3 tbsp soy sauce', '1 tbsp sesame oil', '2 garlic cloves', '1 tsp fresh ginger', '1 tbsp cornflour'],
    steps: [
      'Mix chicken with cornflour and a tablespoon of soy sauce.',
      'Heat sesame oil in a wok over high heat. Stir-fry chicken for 5–6 minutes until golden.',
      'Add garlic and ginger. Cook for 30 seconds.',
      'Add vegetables and remaining soy sauce. Stir-fry for 3–4 minutes until veg is tender-crisp.',
      'Serve over rice or noodles.',
    ],
  },
  {
    id: 'baked-salmon-sweet-potato',
    name: 'Baked Salmon with Sweet Potato',
    emoji: '🍠',
    mealType: 'dinner',
    calories: 530,
    proteinG: 44,
    prepMinutes: 30,
    costGBP: 5.50,
    tags: ['Omega-3', 'High protein', 'Healthy fats'],
    description: 'Classic healthy dinner — baked salmon with sweet potato and tenderstem broccoli.',
    ingredients: ['200g salmon fillet', '1 large sweet potato', '150g tenderstem broccoli', '1 tbsp olive oil', '1 garlic clove', '½ lemon', 'Paprika', 'Salt and pepper'],
    steps: [
      'Preheat oven to 200°C. Cube sweet potato, toss with olive oil and paprika, roast for 20 minutes.',
      'Season salmon with garlic, lemon juice, salt, and pepper. Place on a lined baking tray.',
      'After 20 minutes, add salmon to the oven alongside the sweet potato. Bake for 12–15 minutes.',
      'Steam or boil broccoli for 3–4 minutes.',
      'Serve everything together with a squeeze of lemon.',
    ],
  },
  {
    id: 'turkey-bolognese',
    name: 'Turkey Mince Bolognese',
    emoji: '🍝',
    mealType: 'dinner',
    calories: 520,
    proteinG: 48,
    prepMinutes: 30,
    costGBP: 4.20,
    tags: ['High protein', 'Lower fat', 'Family favourite'],
    description: 'All the comfort of a classic spag bol with turkey mince instead — leaner and just as tasty.',
    ingredients: ['400g turkey mince', '1 onion', '2 garlic cloves', '400g tin chopped tomatoes', '2 tbsp tomato purée', '1 tsp dried oregano', '300g wholewheat spaghetti', '1 tbsp olive oil'],
    steps: [
      'Cook spaghetti according to packet instructions.',
      'Heat oil in a pan. Fry onion and garlic until softened, about 5 minutes.',
      'Add turkey mince. Brown well, breaking up lumps.',
      'Stir in tomatoes, tomato purée, and oregano. Simmer for 15 minutes.',
      'Season generously and serve over spaghetti.',
    ],
  },
  {
    id: 'chicken-tikka',
    name: 'Lighter Chicken Tikka Masala',
    emoji: '🍛',
    mealType: 'dinner',
    calories: 490,
    proteinG: 46,
    prepMinutes: 30,
    costGBP: 4.00,
    tags: ['High protein', 'Family favourite'],
    description: 'A lighter version of the nation\'s favourite — big flavour, less cream. Serve with basmati rice.',
    ingredients: ['400g chicken breast (diced)', '1 onion', '2 garlic cloves', '1 tin coconut milk (light)', '2 tbsp tikka masala paste', '400g chopped tomatoes', '1 tbsp Greek yoghurt', 'Fresh coriander'],
    steps: [
      'Fry onion and garlic in oil for 5 minutes. Add tikka paste and cook for 2 minutes.',
      'Add chicken and brown on all sides.',
      'Pour in tomatoes and coconut milk. Simmer for 20 minutes until chicken is cooked through.',
      'Stir in yoghurt off the heat.',
      'Scatter coriander and serve with basmati rice.',
    ],
  },
  {
    id: 'beef-broccoli-bowl',
    name: 'Beef & Broccoli Rice Bowl',
    emoji: '🥩',
    mealType: 'dinner',
    calories: 490,
    proteinG: 42,
    prepMinutes: 20,
    costGBP: 4.80,
    tags: ['High protein', 'Quick'],
    description: 'Lean beef strips with broccoli in a sticky soy glaze over fluffy white rice.',
    ingredients: ['300g lean beef steak (sliced thin)', '200g broccoli', '200g cooked rice', '3 tbsp soy sauce', '1 tbsp oyster sauce', '1 tsp sesame oil', '2 garlic cloves', '1 tsp cornflour'],
    steps: [
      'Toss beef in cornflour and 1 tbsp soy sauce.',
      'Blanch broccoli in boiling water for 2 minutes. Drain.',
      'Sear beef in a hot pan for 3–4 minutes. Remove and set aside.',
      'Fry garlic for 30 seconds. Add broccoli, remaining soy sauce, and oyster sauce.',
      'Return beef to pan, toss to coat, drizzle sesame oil, and serve over rice.',
    ],
  },
  {
    id: 'grilled-chicken-roast-veg',
    name: 'Grilled Chicken with Roasted Veg',
    emoji: '🫑',
    mealType: 'dinner',
    calories: 420,
    proteinG: 48,
    prepMinutes: 40,
    costGBP: 4.50,
    tags: ['High protein', 'Low carb', 'Meal prep'],
    description: 'Herby grilled chicken thighs with a tray of colourful roasted vegetables. Dead easy.',
    ingredients: ['4 chicken thighs (skinless)', '1 red pepper', '1 courgette', '1 red onion', '200g cherry tomatoes', '2 tbsp olive oil', '1 tsp dried mixed herbs', 'Garlic powder', 'Lemon'],
    steps: [
      'Preheat oven to 200°C.',
      'Chop veg into large chunks. Toss with 1 tbsp olive oil, salt, and pepper on a large tray. Roast for 20 minutes.',
      'Season chicken with herbs, garlic powder, salt, and remaining olive oil.',
      'Push veg to the sides, add chicken to the tray, and roast for a further 20–25 minutes.',
      'Squeeze lemon over before serving.',
    ],
  },
  {
    id: 'prawn-thai-curry',
    name: 'Prawn & Vegetable Thai Curry',
    emoji: '🦐',
    mealType: 'dinner',
    calories: 460,
    proteinG: 38,
    prepMinutes: 20,
    costGBP: 5.50,
    tags: ['High protein', 'Quick', 'Low fat'],
    description: 'Fragrant Thai green curry packed with king prawns and vegetables. Light but satisfying.',
    ingredients: ['300g raw king prawns', '1 tin light coconut milk', '2 tbsp Thai green curry paste', '1 courgette', '1 red pepper', '100g spinach', 'Fish sauce', 'Fresh basil or coriander'],
    steps: [
      'Fry curry paste in a pan for 1 minute until fragrant.',
      'Pour in coconut milk. Bring to a simmer.',
      'Add courgette and pepper. Simmer for 5 minutes.',
      'Add prawns and cook for 3–4 minutes until pink.',
      'Stir in spinach until wilted. Season with fish sauce.',
      'Serve with jasmine rice and fresh herbs.',
    ],
  },
  {
    id: 'chicken-chickpea-stew',
    name: 'Chicken & Chickpea Stew',
    emoji: '🫘',
    mealType: 'dinner',
    calories: 480,
    proteinG: 46,
    prepMinutes: 35,
    costGBP: 3.80,
    tags: ['High protein', 'High fibre', 'Budget friendly'],
    description: 'A warming one-pot stew with chicken, chickpeas, and tomatoes. Freezes brilliantly.',
    ingredients: ['400g chicken breast (diced)', '400g tin chickpeas (drained)', '400g tin chopped tomatoes', '1 onion', '2 garlic cloves', '1 tsp smoked paprika', '1 tsp cumin', '500ml chicken stock', '1 tbsp olive oil'],
    steps: [
      'Brown chicken in oil over high heat. Remove and set aside.',
      'Fry onion and garlic for 5 minutes. Add paprika and cumin.',
      'Return chicken to pan. Add tomatoes, chickpeas, and stock.',
      'Simmer uncovered for 20 minutes until slightly thickened.',
      'Season generously. Serve with crusty bread or rice.',
    ],
  },
  {
    id: 'cod-sweet-potato-chips',
    name: 'Baked Cod & Sweet Potato Chips',
    emoji: '🐟',
    mealType: 'dinner',
    calories: 430,
    proteinG: 42,
    prepMinutes: 35,
    costGBP: 4.00,
    tags: ['High protein', 'Low fat', 'Family favourite'],
    description: 'Healthy fish and chips — baked not fried. Crispy sweet potato wedges and flaky cod.',
    ingredients: ['2 cod fillets', '2 sweet potatoes', '1 tbsp olive oil', '1 tsp paprika', '1 tsp garlic powder', 'Lemon', 'Salt and pepper'],
    steps: [
      'Preheat oven to 210°C.',
      'Cut sweet potatoes into thick wedges. Toss with oil, paprika, and garlic. Roast for 25 minutes, turning once.',
      'Season cod with salt, pepper, and a squeeze of lemon.',
      'Add cod to the oven for the last 12–15 minutes.',
      'Serve with peas and a wedge of lemon.',
    ],
  },

  // ─── SNACKS ─────────────────────────────────────────────────────────────────
  {
    id: 'greek-yoghurt-honey',
    name: 'Greek Yoghurt with Honey & Walnuts',
    emoji: '🍯',
    mealType: 'snack',
    calories: 200,
    proteinG: 14,
    prepMinutes: 2,
    costGBP: 0.90,
    tags: ['High protein', 'No cook', 'Quick'],
    description: 'A satisfying snack that feels indulgent but isn\'t. The walnuts add crunch and healthy fats.',
    ingredients: ['150g full-fat Greek yoghurt', '1 tsp honey', '15g walnuts (roughly chopped)'],
    steps: ['Spoon yoghurt into a bowl.', 'Drizzle honey over the top.', 'Scatter walnuts and serve.'],
  },
  {
    id: 'apple-peanut-butter',
    name: 'Apple with Peanut Butter',
    emoji: '🍎',
    mealType: 'snack',
    calories: 210,
    proteinG: 5,
    prepMinutes: 2,
    costGBP: 0.70,
    tags: ['Healthy fats', 'No cook', 'Quick'],
    description: 'The classic snack combo. Sweet apple with creamy peanut butter keeps hunger at bay.',
    ingredients: ['1 large apple', '2 tbsp natural peanut butter (no added sugar)'],
    steps: ['Core and slice the apple.', 'Serve with peanut butter on the side for dipping.'],
  },
  {
    id: 'boiled-eggs',
    name: 'Boiled Eggs',
    emoji: '🥚',
    mealType: 'snack',
    calories: 155,
    proteinG: 13,
    prepMinutes: 10,
    costGBP: 0.60,
    tags: ['High protein', 'Meal prep', 'Budget friendly'],
    description: 'The most portable high-protein snack there is. Batch cook 6 at the start of the week.',
    ingredients: ['2 eggs', 'Pinch of sea salt'],
    steps: [
      'Bring a small pan of water to the boil.',
      'Lower eggs in gently on a spoon.',
      'Boil for 7 minutes for a set yolk, 6 for slightly jammy.',
      'Cool in cold water for 2 minutes before peeling.',
    ],
  },
  {
    id: 'mixed-nuts',
    name: 'Mixed Nuts & Seeds',
    emoji: '🥜',
    mealType: 'snack',
    calories: 185,
    proteinG: 5,
    prepMinutes: 1,
    costGBP: 0.80,
    tags: ['Healthy fats', 'No cook', 'Quick'],
    description: 'A handful of mixed nuts and seeds is one of the most nutrient-dense snacks you can eat.',
    ingredients: ['30g mixed nuts (almonds, cashews, walnuts)', '10g mixed seeds (pumpkin, sunflower)'],
    steps: ['Measure into a small bowl or bag.', 'That\'s it. Eat and enjoy.'],
  },
  {
    id: 'cottage-cheese-rice-cakes',
    name: 'Cottage Cheese & Rice Cakes',
    emoji: '🧀',
    mealType: 'snack',
    calories: 170,
    proteinG: 18,
    prepMinutes: 2,
    costGBP: 0.75,
    tags: ['High protein', 'Low calorie', 'No cook'],
    description: 'Surprisingly filling for the calories. Cottage cheese on rice cakes with a sprinkle of black pepper.',
    ingredients: ['3 plain rice cakes', '100g cottage cheese', 'Black pepper', 'Optional: sliced cucumber or tomato'],
    steps: ['Spoon cottage cheese onto rice cakes.', 'Season with black pepper.', 'Top with cucumber or tomato slices if using.'],
  },
]

export const getMealsByType = (type: LibraryMeal['mealType']) =>
  mealLibrary.filter((m) => m.mealType === type)

export const getAllTypes = (): LibraryMeal['mealType'][] =>
  ['breakfast', 'lunch', 'dinner', 'snack']

export const mealTypeLabel: Record<LibraryMeal['mealType'], string> = {
  breakfast: 'Breakfast',
  lunch: 'Lunch',
  dinner: 'Dinner',
  snack: 'Snack',
}
