export type Exercise = {
  id: string
  name: string
  category: 'lower-body' | 'upper-body' | 'core' | 'cardio' | 'full-body'
  muscles: string[]
  difficulty: 'beginner' | 'intermediate' | 'advanced'
  sets: number
  reps: string // e.g. "10-15" or "30 seconds"
  restSeconds: number
  instructions: string[]
  tips: string[]
  calories: number // approx per set
  emoji: string
  imageUrl?: string
}

export const exercises: Exercise[] = [
  {
    id: 'squat',
    name: 'Bodyweight Squat',
    category: 'lower-body',
    muscles: ['Quads', 'Glutes', 'Hamstrings', 'Core'],
    difficulty: 'beginner',
    sets: 3,
    reps: '12-15',
    restSeconds: 60,
    emoji: '🦵',
    calories: 8,
    instructions: [
      'Stand with feet shoulder-width apart, toes slightly turned out',
      'Push your hips back and bend your knees, as if sitting into a chair',
      'Lower until thighs are parallel to the floor (or as low as comfortable)',
      'Keep your chest up and knees tracking over your toes',
      'Drive through your heels to stand back up',
    ],
    tips: ['Go slow on the way down — 3 seconds down, 1 second up', 'Keep your weight in your heels', 'Squeeze glutes at the top'],
    imageUrl: '/images/exercises/bodyweight-squat.webp',
  },
  {
    id: 'push-up',
    name: 'Press-Up (Push-Up)',
    category: 'upper-body',
    muscles: ['Chest', 'Triceps', 'Shoulders', 'Core'],
    difficulty: 'beginner',
    sets: 3,
    reps: '8-12',
    restSeconds: 60,
    emoji: '💪',
    calories: 7,
    instructions: [
      'Start in a high plank: hands slightly wider than shoulder-width',
      'Keep your body in a straight line from head to heels',
      'Lower your chest towards the floor by bending your elbows',
      'Keep elbows at roughly 45° from your torso (not flared wide)',
      'Push back up to starting position',
    ],
    tips: ['Can\'t do full ones? Start on your knees — that\'s fine', 'Avoid letting hips sag or pike up', 'Slow and controlled beats fast and sloppy'],
    imageUrl: '/images/exercises/press-up.webp',
  },
  {
    id: 'plank',
    name: 'Plank Hold',
    category: 'core',
    muscles: ['Core', 'Shoulders', 'Glutes'],
    difficulty: 'beginner',
    sets: 3,
    reps: '20-45 seconds',
    restSeconds: 45,
    emoji: '🏋️',
    calories: 5,
    instructions: [
      'Rest on your forearms and toes, elbows directly under your shoulders',
      'Keep your body in a straight line — no sagging hips or raised bum',
      'Squeeze your abs, glutes, and thighs throughout',
      'Breathe steadily — don\'t hold your breath',
      'Hold for the target time',
    ],
    tips: ['Focus on quality over time — 20 perfect seconds beats 60 sloppy ones', 'Stare at the floor to keep neck neutral', 'Build up time gradually each week'],
    imageUrl: '/images/exercises/plank-hold.webp',
  },
  {
    id: 'lunge',
    name: 'Reverse Lunge',
    category: 'lower-body',
    muscles: ['Quads', 'Glutes', 'Hamstrings', 'Balance'],
    difficulty: 'beginner',
    sets: 3,
    reps: '10 each leg',
    restSeconds: 60,
    emoji: '🦵',
    calories: 9,
    instructions: [
      'Stand tall, feet hip-width apart',
      'Step one foot backwards, lowering your back knee towards the floor',
      'Front thigh should be roughly parallel to the floor',
      'Keep your torso upright — don\'t lean forward',
      'Push through your front heel to return to start, then alternate legs',
    ],
    tips: ['Reverse lunges are easier on the knees than forward lunges', 'Hold on to a wall if balance is an issue', 'Keep front knee directly over your ankle'],
    imageUrl: '/images/exercises/reverse-lunge.webp',
  },
  {
    id: 'burpee',
    name: 'Burpee',
    category: 'full-body',
    muscles: ['Full Body', 'Cardio'],
    difficulty: 'intermediate',
    sets: 3,
    reps: '8-10',
    restSeconds: 90,
    emoji: '🔥',
    calories: 12,
    instructions: [
      'Stand with feet shoulder-width apart',
      'Drop into a squat and place hands on the floor',
      'Jump or step both feet back into a plank position',
      'Optionally do a press-up here',
      'Jump or step feet back to your hands, then explosively jump up with arms overhead',
    ],
    tips: ['No shame in stepping instead of jumping — same muscles, less impact', 'Rest more between sets if needed — these are tough', 'Brilliant for burning fat in short sessions'],
    imageUrl: '/images/exercises/burpee.webp',
  },
  {
    id: 'mountain-climber',
    name: 'Mountain Climbers',
    category: 'cardio',
    muscles: ['Core', 'Shoulders', 'Hip Flexors', 'Cardio'],
    difficulty: 'intermediate',
    sets: 3,
    reps: '30 seconds',
    restSeconds: 45,
    emoji: '⛰️',
    calories: 10,
    instructions: [
      'Start in a high plank position, hands under shoulders',
      'Drive your right knee towards your chest',
      'Quickly switch — drive left knee in as right leg extends back',
      'Continue alternating at a controlled pace',
      'Keep hips level — don\'t let them rise or sag',
    ],
    tips: ['Slower = more core work. Faster = more cardio', 'Keep breathing throughout', 'Great for burning calories without equipment'],
    imageUrl: '/images/exercises/mountain-climbers.webp',
  },
  {
    id: 'glute-bridge',
    name: 'Glute Bridge',
    category: 'lower-body',
    muscles: ['Glutes', 'Hamstrings', 'Lower Back'],
    difficulty: 'beginner',
    sets: 3,
    reps: '15-20',
    restSeconds: 45,
    emoji: '🍑',
    calories: 6,
    instructions: [
      'Lie on your back, knees bent, feet flat on the floor hip-width apart',
      'Press through your heels and squeeze your glutes to lift your hips',
      'Raise until your body forms a straight line from shoulders to knees',
      'Hold for 1-2 seconds at the top',
      'Lower slowly back to the floor',
    ],
    tips: ['Brilliant for men who sit all day — fires up inactive glutes', 'Pause and squeeze hard at the top', 'Can make harder by extending one leg'],
    imageUrl: '/images/exercises/glute-bridge.webp',
  },
  {
    id: 'jumping-jacks',
    name: 'Jumping Jacks',
    category: 'cardio',
    muscles: ['Full Body', 'Cardio'],
    difficulty: 'beginner',
    sets: 3,
    reps: '30 seconds',
    restSeconds: 30,
    emoji: '⚡',
    calories: 8,
    instructions: [
      'Stand upright with feet together, arms by your sides',
      'Jump your feet out to the sides while raising both arms overhead',
      'Land softly with feet wider than shoulder-width',
      'Jump back to start position, bringing feet together and arms down',
      'Repeat rhythmically',
    ],
    tips: ['Good warm-up exercise before a workout', 'Land softly to protect your knees and joints', 'Can step side-to-side instead of jumping to reduce impact'],
    imageUrl: '/images/exercises/jumping-jacks.webp',
  },
  {
    id: 'tricep-dip',
    name: 'Chair Tricep Dip',
    category: 'upper-body',
    muscles: ['Triceps', 'Shoulders', 'Chest'],
    difficulty: 'beginner',
    sets: 3,
    reps: '10-12',
    restSeconds: 60,
    emoji: '🪑',
    calories: 6,
    instructions: [
      'Sit on the edge of a sturdy chair, hands gripping the edge beside your hips',
      'Slide your bum off the seat, supporting your weight on your arms',
      'Lower yourself by bending your elbows to roughly 90°',
      'Keep your back close to the chair throughout',
      'Press back up to starting position',
    ],
    tips: ['Feet closer to you = easier. Feet further out = harder', 'Keep elbows pointing straight back, not flaring sideways', 'Use a sturdy chair or bench — not a wheeled office chair!'],
  },
  {
    id: 'high-knees',
    name: 'High Knees',
    category: 'cardio',
    muscles: ['Hip Flexors', 'Core', 'Cardio'],
    difficulty: 'beginner',
    sets: 3,
    reps: '30 seconds',
    restSeconds: 30,
    emoji: '🏃',
    calories: 9,
    instructions: [
      'Stand with feet hip-width apart',
      'Run on the spot, driving each knee up to hip height',
      'Pump your arms in rhythm with your legs',
      'Land lightly on the balls of your feet',
      'Maintain an upright posture throughout',
    ],
    tips: ['Great indoor cardio when the weather is awful', 'Drive arms to increase intensity', 'Can slow down to a march if needed — still burns calories'],
  },
  {
    id: 'superman',
    name: 'Superman Hold',
    category: 'core',
    muscles: ['Lower Back', 'Glutes', 'Core'],
    difficulty: 'beginner',
    sets: 3,
    reps: '10-12',
    restSeconds: 45,
    emoji: '🦸',
    calories: 4,
    instructions: [
      'Lie face down on the floor, arms extended in front of you',
      'Simultaneously lift your arms, chest, and legs off the floor',
      'Hold for 2-3 seconds at the top',
      'Lower slowly back to the floor',
      'Repeat for reps',
    ],
    tips: ['Brilliant for men with lower back issues or who sit at a desk all day', 'Don\'t strain your neck — look at the floor', 'Builds the posterior chain which most desk workers neglect'],
  },
  {
    id: 'wall-sit',
    name: 'Wall Sit',
    category: 'lower-body',
    muscles: ['Quads', 'Glutes', 'Core'],
    difficulty: 'beginner',
    sets: 3,
    reps: '30-45 seconds',
    restSeconds: 60,
    emoji: '🧱',
    calories: 7,
    instructions: [
      'Stand with your back against a wall',
      'Slide down until your thighs are parallel to the floor',
      'Knees directly over ankles, back flat against wall',
      'Hold the position for the target time',
      'Slide back up to standing to rest',
    ],
    tips: ['Burns more than you\'d expect — great for legs and fat loss', 'Don\'t let knees cave inward', 'Can make harder by holding a weight on your thighs'],
  },
]

export const workoutPlans = [
  {
    id: 'beginner-fat-loss',
    name: 'Beginner Fat Burner',
    description: '3x per week, no equipment, 20-25 minutes',
    exercises: ['jumping-jacks', 'squat', 'push-up', 'glute-bridge', 'plank', 'high-knees'],
    targetMinutes: 25,
    difficulty: 'beginner' as const,
    emoji: '🔥',
  },
  {
    id: 'full-body-blast',
    name: 'Full Body Blast',
    description: '3x per week, high intensity, 30 minutes',
    exercises: ['burpee', 'squat', 'mountain-climber', 'push-up', 'lunge', 'plank'],
    targetMinutes: 30,
    difficulty: 'intermediate' as const,
    emoji: '⚡',
  },
  {
    id: 'core-strength',
    name: 'Core & Posture',
    description: 'Daily, 15 minutes — great for desk workers',
    exercises: ['plank', 'glute-bridge', 'superman', 'mountain-climber', 'wall-sit'],
    targetMinutes: 15,
    difficulty: 'beginner' as const,
    emoji: '🏋️',
  },
]

export const categories = [
  { id: 'all', label: 'All exercises', emoji: '🏠' },
  { id: 'lower-body', label: 'Lower body', emoji: '🦵' },
  { id: 'upper-body', label: 'Upper body', emoji: '💪' },
  { id: 'core', label: 'Core', emoji: '🏋️' },
  { id: 'cardio', label: 'Cardio', emoji: '🏃' },
  { id: 'full-body', label: 'Full body', emoji: '🔥' },
]
